name: Build and push to docker hub

on: [push]

jobs:
  docker-build-and-push:
    name: Build docker image and push
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        sc2-version: ['4.10']

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: burnysc2/python-sc2-docker:py_${{ matrix.python-version }}-sc2_${{ matrix.sc2-version }}-v1.0.0
          build-args: ['PYTHON_VERSION=${{ matrix.python-version }}', 'SC2_VERSION=${{ matrix.sc2-version }}']
      if: needs.check-for-existing-docker-image.outputs.tag-exists != 'true'
